### PR TITLE
Handle empty branches

### PR DESCRIPTION
**Pull request by dtaniwaki**
I thought I handled empty commits and diff branches, but I realized I didn't.

### CODE REVIEW

**Comment by everpeace** [comment]
How about output commit hash and diff hash instead of outputting nothing.

**Comment by dtaniwaki** [comment]
> How about output commit hash and diff hash instead of outputting nothing?

I think the change of this PR provides the feature.

**Comment by everpeace** [comment]
Am I missing something??

```
# build
(~/go_projects/git-ghost/src/git-ghost)
 [handle-empty-branch|✚ 1…2⚑ 1] $ make
dep ensure
go build -tags netgo -installsuffix netgo -ldflags="-s -w -X \"github.com/pfnet-research/git-ghost/cmd.Version=v0.1.1-dev\" -X \"github.com/pfnet-research/git-ghost/cmd.Revision=0f56d0f\" -extldflags \"-static\"" -o /Users/everpeace/go_projects/git-ghost/src/git-ghost/dist/git-ghost

(~/go_projects/git-ghost/src/git-ghost)
 [handle-empty-branch|✚ 1…2⚑ 1] $ make install
dep ensure
go install -tags netgo -installsuffix netgo -ldflags="-s -w -X \"github.com/pfnet-research/git-ghost/cmd.Version=v0.1.1-dev\" -X \"github.com/pfnet-research/git-ghost/cmd.Revision=0f56d0f\" -extldflags \"-static\""

# at repo
$ git remote -v
origin  git@github.pfidev.jp:omura/git-ghost-test.git (fetch)
origin  git@github.pfidev.jp:omura/git-ghost-test.git (push)

$ export | grep GIT_GHOST
declare -x GIT_GHOST_REPO="git@github.pfidev.jp:omura/git-ghost-test.git"

$ git status
HEAD detached at 0563ef1
nothing to commit, working tree clean

$ ~/go_projects/git-ghost/bin/git-ghost push
## Nothing output ###
```

**Comment by everpeace** [comment]
I confirmed your change correctly works!  Thanks!

**Pull request merged**
